#!/usr/bin/env python
import roslib; roslib.load_manifest('ros_monitor')
import sys, time
import rospy

from ros_monitor.node_info import NodeInfo
from ros_monitor.process_info import ProcessInfo
from ros_monitor.msg import Stats, NodeStats, ConnectionStats

class RosMonitor:
   def __init__(self):
      self.ni = NodeInfo()
      self.pi = ProcessInfo()
      self.stat_pub = rospy.Publisher('/ros_monitor/stats', Stats)

   def run(self):
      update_rate = rospy.Rate(1.0)
      while not rospy.is_shutdown():
         self.run_once()
         update_rate.sleep()
      
   def run_once(self):
      stats_msg = Stats()
      stats_msg.header.stamp = rospy.Time.now()
      
      nodes = self.ni.get_nodes()
      pids = [nodes[node_name]['pid'] for node_name in nodes.keys()]
      process_info = self.pi.get_stats(pids)
      
      pids = []
      for node_name in nodes:
         node_stats_msg = NodeStats()
         node_stats_msg.node_name = node_name
         node_dict = nodes[node_name]
         pid = node_dict['pid']

         node_stats_msg.pcpu = process_info[pid]['pcpu']
         node_stats_msg.vsz = process_info[pid]['vsz']

         print '%20s (%d): %5.1f %d' % (node_name[:18], pid, process_info[pid]['pcpu'], process_info[pid]['vsz'])

         stats_msg.node_stats.append(node_stats_msg)
         
      self.stat_pub.publish(stats_msg)

if __name__ == '__main__':
   rospy.init_node('ros_monitor', anonymous=True)
   
   rm = RosMonitor()
   rm.run()
   

