#!/usr/bin/env python
PACKAGE_NAME = 'ros_monitor'
import roslib; roslib.load_manifest(PACKAGE_NAME)
import sys, time, socket
import rospy

from ros_monitor.process_stats_node import ProcessStatsNode

hostname = socket.gethostname()
rospy.init_node('ps_monitor_%s' % hostname, anonymous=True)
psn = ProcessStatsNode()
psn.run()
